### ISSUE TITLE
Incorrect docs for app option

### ISSUE THREAD

**Issue by levithomason** [stevelacy/gulp-open#14]
Love the plugin, used it on a few projects for a while now.

**The Issue**
Here is my gulp task which does not open chrome:
```javascript
gulp.task('open', function() {
    return gulp.src('./index.html')
        .pipe(open('', {
            url: 'http://localhost:8000',
            app: 'chrome'  // "chrome" per the docs
        }));
});
```
**The Fix**
Using `app: 'google chrome'` does work and is case insensitive.

**System Info**
Mac OSX Mavericks (10.10.1)

gulp-open 0.3.1

Gulp
CLI version 3.8.9
Local version 3.8.10

Thanks!

**Comment by stevelacy** [comment]
The docs clearly state the current OS's tested: https://github.com/stevelacy/gulp-open#optionsapp
It does not have a entry for OSX.

I will add one.

**Comment by levithomason** [comment]
You are correct.  Thanks for the update.
