### ISSUE TITLE
Feature Request: options arguments

### ISSUE THREAD

**Issue by calekennedy** [stevelacy/gulp-open#18]
It would be really nice to be able to pass options arguments to the plugin

i.e., 

```
gulp.task('open-chrome', function(){
  var options = {
    uri: 'http://localhost:3000',
    app: 'chrome',
    options: '--open-fullscreen'
  };
  gulp.src(__filename)
  .pipe(open(options));
});

```

**Comment by stevelacy** [comment]
`node-open` must first support the optional arguments: https://github.com/pwnall/node-open

**Comment by stevelacy** [comment]
I will probably switch open to opn https://www.npmjs.com/package/opn

**Comment by stevelacy** [comment]
switched to opn
