### ISSUE TITLE
can open browser and enable dev tools(eg: chrome dev tools)

### ISSUE THREAD

**Issue by Harvey-he** [stevelacy/gulp-open#22]
Is it possible to open chrome and enable dev tools?

**Comment by stevelacy** [comment]
No

https://code.google.com/p/chromium/issues/detail?id=410958

http://stackoverflow.com/questions/12212504/automatically-open-chrome-developer-tools-when-new-tab-new-window-is-opened

**Comment by Harvey-he** [comment]
OK THX
