### ISSUE TITLE
Browser Url error

### ISSUE THREAD

**Issue by henjue** [stevelacy/gulp-open#25]
## Code as follows
```nodejs
gulp.src('./src/index.html')
.pipe(open({url: 'http://localhost:8080/'}));
```
0.3.1 version normal open http://localhost:8080,
after the upgrade to open the browser 1.0.0 default is file:///home/{xxxxxxxx}/src/index.html
should is http://localhost:8080

**Comment by stevelacy** [comment]
Make sure the option is `URI` (u r i ) not `URL` (u r l ) 
https://github.com/stevelacy/gulp-open/releases/tag/1.0.0

Cheers

**Comment by henjue** [comment]
@stevelacy so sorry

**Comment by stevelacy** [comment]
No problem, I'm guessing its working now :smile:

**Comment by henjue** [comment]
@stevelacy yes.very good,thk
