### ISSUE TITLE
Feature Request: only open if not already open

### ISSUE THREAD

**Issue by xetra11** [stevelacy/gulp-open#26]
Feature Request:

Hey there!

Can you implement an option to forbid opening if the url to open is already open?

greets Charlie

**Comment by stevelacy** [comment]
due to browser's not sending data back to gulp, there is no way to determine the current process in another application without some crazy memory checking management.

**Comment by gigablox** [comment]
If this task is inside a watch, you could wrap it in a condition with a "once" variable.
