### ISSUE TITLE
Can't find gulp-open

### ISSUE THREAD

**Issue by fernandofas** [stevelacy/gulp-open#28]
Hi all,

Just a quick question.

I installed Gulp-open with the following codes on gulpfiles.js:

gulp.task( 'open', function() {
var options = {
uri: uri,
app: 'chrome' || 'google chrome' // may need to sniff for Windows/OSX to determine Chrome string
};
gulp.src( './build/' )
.pipe( open( options ) );
});

I also have gulp-connect and gulp-yargs with the following:

var src = './build',
dist = './build',
baseURL = ( argv.production === undefined ) ? src : dist,
port = ( argv.production === undefined ) ? 8000 : 8001,
uri = 'http://localhost:' + port;

gulp.task( 'connect', function() {
connect.server( {
root: baseURL,
livereload: true,
port: port
} );
} );

I'm not sure what is happening, on the package.json the dependency is there, but gulp can't find it.

Any ideas what's happening?

Thank you in advance.

Kind regards,

Fernando Fas

**Comment by stevelacy** [comment]
Please add your gulpfile and the npm erro

**Comment by fernandofas** [comment]
There you go:

var gulp = require('gulp');
var gutil = require('gulp-util');
var sass = require('gulp-sass');
var postcss = require('gulp-postcss');
var scss = require('postcss-scss');
var autoprefixer = require('autoprefixer');
var inlineCss = require('gulp-inline-css');
var nunjucksRender = require('gulp-nunjucks-render');
var data = require('gulp-data');
var zip = require('gulp-zip');
var connect = require('gulp-connect');
var htmlmin = require('gulp-htmlmin');
var runSequence = require('run-sequence');
var express = require( 'express' );
var argv = require( 'yargs' ).argv;
var open = require( 'gulp-open' );
var connect = require( 'gulp-connect' );

/*CONFIG*/
gulp.task( 'server', [ 'serve' ] );
gulp.task( 'serve', [ 'connect', 'open', 'watch' ] );
gulp.task('default', function(callback) {
  runSequence('server', 'connect', 'nunjucks', 'inlinecss', 'minify', 'watch', ['minify', 'zip'],
              callback);});

var globalData = {
    email: require('./src/data/email.json')
};

var src = './build',
    dist = './build',
    baseURL = ( argv.production === undefined ) ? src : dist,
    port = ( argv.production === undefined ) ? 8000 : 8001,
    uri = 'http://localhost:' + port;


gulp.task( 'connect', function() {
    connect.server( {
        root: baseURL,
        livereload: true,
        port: port
    } );
} );

gulp.task( 'open', function() {
    var options = {
        uri: uri,
        app: 'chrome' || 'google chrome' // may need to sniff for Windows/OSX to determine Chrome string
    };
    gulp.src( './build/' )
        .pipe( open( options ) );
});


/*CSS*/

var postcssProcessors = [
    autoprefixer( { browsers: ['last 2 versions', 'ie > 10'] } )
]

gulp.task('sassInline', function(callback) {
    return gulp.src('src/sass/inline.scss')
        .pipe(
           postcss(postcssProcessors, {syntax: scss})
        )
        .pipe(
            sass({ outputStyle: 'expanded' })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/css/'));
});

gulp.task('sassEmbedded', function(callback) {
    return gulp.src('src/sass/embedded.scss')
        .pipe(
           postcss(postcssProcessors, {syntax: scss})
        )
        .pipe(
            sass({ outputStyle: 'compressed' })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/css/')); 
});

gulp.task('sassMq', function(callback) {
    return gulp.src('src/sass/mq.scss')
        .pipe(
           postcss(postcssProcessors, {syntax: scss})
        )
        .pipe(
            sass({ outputStyle: 'compressed' })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/css/')); 
});

gulp.task('inlinecss', ['sassInline', 'nunjucks'], function() {
    return gulp.src('build/*.html')
        .pipe(
            inlineCss({
                applyStyleTags: false,
                removeStyleTags: false
            })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/'));
});

/*TEMPLATING*/

gulp.task('nunjucks', ['sassEmbedded', 'sassMq'], function() {
    return gulp.src('src/emails/*.nunjucks')
        .pipe(
            data(function() {
                return globalData;
            })
            .on('error', gutil.log)
        )
        .pipe(
            nunjucksRender({
                path: ['src/templates/', 'build/css/']
            })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/'));
});

/*ZIP*/

gulp.task('zip', function () {
    return gulp.src('build/*.html')
        .pipe(zip('build.zip'))
        .pipe(gulp.dest('build/'));
});

/*SERVER*/

gulp.task('connect', function() {
    connect.server({
        port: 8000
    });
});

/*WATCH*/

var filesToWatch = [
    'src/sass/**/*.scss',
    'src/emails/*.nunjucks',
    'src/templates/**/*.nunjucks',
    'src/data/*.json'
]

gulp.task('watch', function() {
    gulp.watch(filesToWatch,['nunjucks', 'inlinecss']); 
});

/*MINIFY HTML*/

gulp.task('minify', function() {
  return gulp.src('build/*.html')
    .pipe(htmlmin({collapseWhitespace: true}))
    .pipe(gulp.dest('build/'));
});

**Comment by stevelacy** [comment]
npm error log?

**Comment by fernandofas** [comment]
nope

**Comment by fernandofas** [comment]
C:\Users\*******\Desktop\Emailtest>gulp
[17:42:47] Using gulpfile ~\Desktop\Emailtest\gulpfile.js
[17:42:47] Starting 'default'...
[17:42:47] Starting 'connect'...
[17:42:47] Finished 'connect' after 14 ms
[17:42:47] Starting 'open'...
[17:42:47] Finished 'open' after 6.78 ms
[17:42:47] Starting 'watch'...
[17:42:47] Finished 'watch' after 28 ms
[17:42:47] Starting 'serve'...
[17:42:47] Finished 'serve' after 1.51 µs
[17:42:47] Starting 'server'...
[17:42:47] Finished 'server' after 1.51 µs
[17:42:47] Starting 'connect'...
[17:42:47] Finished 'connect' after 592 µs
[17:42:47] Starting 'sassEmbedded'...
[17:42:47] Starting 'sassMq'...
[17:42:47] Server started http://localhost:8000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at ConnectApp.run (C:\Users\******\Desktop\Emailtest\node_modules\gulp
-connect\index.js:77:24)
    at new ConnectApp (C:\Users\******\Desktop\Emailtest\node_modules\gulp
-connect\index.js:48:10)
    at Object.server (C:\Users\******\Desktop\Emailtest\node_modules\gulp-
connect\index.js:207:11)
    at Gulp.<anonymous> (C:\Users\******\Desktop\Emailtest\gulpfile.js:139
:13)
    at module.exports (C:\Users\******\Desktop\Emailtest\node_modules\orch
estrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\******\Desktop\Emailtest\node_
modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\******\Desktop\Emailtest\node_
modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\******\Desktop\Emailtest\node_mod
ules\orchestrator\index.js:134:8)
    at runNextSet (C:\Users\******\Desktop\Emailtest\node_modules\run-sequ
ence\index.js:86:16)
    at Gulp.onTaskEnd (C:\Users\******\Desktop\Emailtest\node_modules\run-
sequence\index.js:75:5)
    at emitOne (events.js:101:20)

**Comment by stevelacy** [comment]
```
events.js:160
throw er; // Unhandled 'error' event
^

Error: listen EADDRINUSE :::8000
```

That is not this plugin, something else is causing you to have two services on that port

**Comment by fernandofas** [comment]
Ok, the issue is fixed, but still not opening the localhost:8000 in the browser.

No errors at all this time.

Gulpfile as follow:

var gulp = require('gulp');
var gutil = require('gulp-util');
var sass = require('gulp-sass');
var postcss = require('gulp-postcss');
var scss = require('postcss-scss');
var autoprefixer = require('autoprefixer');
var inlineCss = require('gulp-inline-css');
var nunjucksRender = require('gulp-nunjucks-render');
var data = require('gulp-data');
var zip = require('gulp-zip');
var connect = require('gulp-connect');
var htmlmin = require('gulp-htmlmin');
var runSequence = require('run-sequence');
var express = require( 'express' );
var argv = require( 'yargs' ).argv;
var open = require( 'gulp-open' );
var connect = require( 'gulp-connect' );

/*CONFIG*/
gulp.task( 'server', [ 'serve' ] );
gulp.task( 'serve', [ 'connect', 'open', 'watch' ] );
gulp.task('default', function(callback) {
  runSequence('connect', 'nunjucks', 'inlinecss', 'minify', 'watch', ['minify', 'zip'],
              callback);});

var globalData = {
    email: require('./src/data/email.json')
};


/*SERVER*/

var src = './build',
    dist = './build',
    baseURL = ( argv.production === undefined ) ? src : dist,
    port = ( argv.production === undefined ) ? 8000 : 8001,
    uri = 'http://localhost:' + port;


gulp.task( 'connect', function() {
    connect.server( {
        root: baseURL,
        livereload: true,
        port: port
    } );
} );

gulp.task( 'open', function() {
    var options = {
        uri: 'uri',
        app: 'chrome' || 'google chrome' // may need to sniff for Windows/OSX to determine Chrome string
    };
    gulp.src( './build/' )
        .pipe( open( options ) );
});


/*CSS*/

var postcssProcessors = [
    autoprefixer( { browsers: ['last 2 versions', 'ie > 10'] } )
]

gulp.task('sassInline', function(callback) {
    return gulp.src('src/sass/inline.scss')
        .pipe(
           postcss(postcssProcessors, {syntax: scss})
        )
        .pipe(
            sass({ outputStyle: 'expanded' })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/css/'));
});

gulp.task('sassEmbedded', function(callback) {
    return gulp.src('src/sass/embedded.scss')
        .pipe(
           postcss(postcssProcessors, {syntax: scss})
        )
        .pipe(
            sass({ outputStyle: 'compressed' })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/css/')); 
});

gulp.task('sassMq', function(callback) {
    return gulp.src('src/sass/mq.scss')
        .pipe(
           postcss(postcssProcessors, {syntax: scss})
        )
        .pipe(
            sass({ outputStyle: 'compressed' })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/css/')); 
});

gulp.task('inlinecss', ['sassInline', 'nunjucks'], function() {
    return gulp.src('build/*.html')
        .pipe(
            inlineCss({
                applyStyleTags: false,
                removeStyleTags: false
            })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/'));
});

/*TEMPLATING*/

gulp.task('nunjucks', ['sassEmbedded', 'sassMq'], function() {
    return gulp.src('src/emails/*.nunjucks')
        .pipe(
            data(function() {
                return globalData;
            })
            .on('error', gutil.log)
        )
        .pipe(
            nunjucksRender({
                path: ['src/templates/', 'build/css/']
            })
            .on('error', gutil.log)
        )
        .pipe(gulp.dest('build/'));
});

/*ZIP*/

gulp.task('zip', function () {
    return gulp.src('build/*.html')
        .pipe(zip('build.zip'))
        .pipe(gulp.dest('build/'));
});


/*WATCH*/

var filesToWatch = [
    'src/sass/**/*.scss',
    'src/emails/*.nunjucks',
    'src/templates/**/*.nunjucks',
    'src/data/*.json'
]

gulp.task('watch', function() {
    gulp.watch(filesToWatch,['nunjucks', 'inlinecss']); 
});

/*MINIFY HTML*/

gulp.task('minify', function() {
  return gulp.src('build/*.html')
    .pipe(htmlmin({collapseWhitespace: true}))
    .pipe(gulp.dest('build/'));
});

**Comment by fernandofas** [comment]
Sorted. uri doesn't need the inverted commas as it's declared as a variable. :/
gulp.task( 'open', function() {
var options = {
uri: **'uri',**
app: 'chrome' || 'google chrome' // may need to sniff for Windows/OSX to determine Chrome string
};
gulp.src( './build/' )
.pipe( open( options ) );
});
