### ISSUE TITLE
open IE

### ISSUE THREAD

**Issue by tatuguerra** [stevelacy/gulp-open#29]
Hi, I would like to know if it is possible to open IE with gulp-open?
thanks

**Comment by stevelacy** [comment]
This plugin can open any program as long as they are listed in the PATH or have a direct path to the binary.
https://superuser.com/questions/113345/how-to-launch-internet-explorer-from-the-command-prompt

**Comment by tatuguerra** [comment]
Thanks, it works perfectly
app: 'iexplore'
