### ISSUE TITLE
`node-open` breaks on Linux - switch to `opn`?

### ISSUE THREAD

**Issue by pretzelface** [stevelacy/gulp-open#30]
You mentioned in https://github.com/stevelacy/gulp-open/issues/18 that you were considering `opn` over `node-open`.

Presently, `node-open` is broken on Linux - I get `Error: spawn open ENOENT` because the `open` command doesn't exist on Linux. A workaround for my use case has been to symlink `xdg-open` to `open`, but that's *super* inelegant, and might well break for other use cases.

Since `node-open` is [deprecated](https://github.com/jjrdn/node-open) anyway, do you anticipate making a switch anytime soon? I'm happy to submit a PR.

**Comment by stevelacy** [comment]
I'll be glad to take a PR, thanks.
