### ISSUE TITLE
Don't check `file.isNull`

### ISSUE THREAD

**Issue by tandrewnichols** [stevelacy/gulp-open#31]
[This line](https://github.com/stevelacy/gulp-open/blob/master/index.js#L17) checks whether the file is null and throws an error if it's not. This prevents users from passing `{ read: false }` to `gulp.src` (because in that case, `file.isNull()` returns true), but since this task _doesn't use the contents of the file_, you should be able to pass `{ read: false }` to optimize the flow (you only need the file path to open it). I realize that means it's possible to attempt to open a file that doesn't exist, but in that case, you'll just get an error, which is no different than the current behavior.

**Comment by stevelacy** [comment]
Yeah, this should allow for passing read: false to the stream.

How does this look? https://github.com/stevelacy/gulp-open/commit/582f888222e9a227632229547b0f1868b428fe5c

**Comment by tandrewnichols** [comment]
Looks good! Thanks for the fast response!

**Comment by stevelacy** [comment]
published to 2.1.0
