### ISSUE TITLE
Can't use directory as uri anymore

### ISSUE THREAD

**Issue by gitsilvan** [stevelacy/gulp-open#33]
In version 2.1.0 I was still able to use directory paths (e.g. "../") as uri and they would open correctly in the desired app (that is _atom_).

In version 3.0 the directory is opened in the default app instead (that is _finder_), although the output in the terminal states that it will be opened in the desired app, and the task runs forever instead of exiting correctly.

I am on macOS.

**Comment by stevelacy** [comment]
Did you specify the `app: atom` in the options?

@TheDancingCode looks like changing to `opn` caused this issue.

**Comment by gitsilvan** [comment]
Yes, both as "atom" and as absolute path.

As mentioned above the output in the terminal also states that the uri will be opened in "atom", but is then opened in the default app / finder and gulp keeps running, not exiting.

Thank you for looking at this!

**Comment by PyvesB** [comment]
Hello there,

I seem to be facing the issue while trying to open a HTML file with a directory path using Firefox. I'll stick to version 2.1.0 for now. Thanks for looking into this. 😉

**Comment by stevelacy** [comment]
Since I am not modifying any part of the options, I'd only suggest figuring out how to open a directory in `opn`. The other unfortunate option is to use 2.1.0.

**Comment by gitsilvan** [comment]
I finally had time to test the new version: now it opens the directory uri in atom as supposed (yay!), but gulp still gets stuck afterwards and won't continue with the next tasks. No errors shown.

**Comment by TheDancingCode** [comment]
Does the task finish when you close atom?

**Comment by silllli** [comment]
No
