### ISSUE TITLE
Process does not exit

### ISSUE THREAD

**Issue by acarnwath** [stevelacy/gulp-open#35]
When I add `.pipe( open() )` to my gulp task, the process never exits - I must hit Cmd+C in order to type the next prompt.  Without this addition, it does exit.

**Comment by stephenlacy** [comment]
Which options are you passing?

**Comment by acarnwath** [comment]
None - just as I have it in the code above.

**Comment by stephenlacy** [comment]
Can you try version 2.1.0 and see if the process hangs?

**Comment by acarnwath** [comment]
The original issue was with 3.0.1, but 2.1.0 does not.

**Comment by stephenlacy** [comment]
Interesting. We switched from using `open` to `opn` in version 3.0.1.
Guessing from the latest release I don't think it is maintained well: https://github.com/sindresorhus/opn
I would suggest staying with version 2.1.0 as we are passing `wait: false` to this option: https://github.com/sindresorhus/opn#wait

**Comment by acarnwath** [comment]
It looks like this could be the issue: https://github.com/sindresorhus/opn/issues/92
I will continue using 2.1.0 for now.

**Comment by stephenlacy** [comment]
Sorry that I couldn't help more
