### ISSUE TITLE
Any way to target a specific google chrome profile?

### ISSUE THREAD

**Issue by colinrippeyfinarne** [stevelacy/gulp-open#36]
First thanks for a great package.

My issue is that i use google chrome profiles to target different user logins on various sites and I wanted to know if it was possible to target a specific profile?

My env is Windows 7, Visual Studio Code, my typical usage is developing SharePoint Spfx solutions to test on lots of different dev/test Office 365 tenants (hence why I have a ton of google chrome profiles and it would be awesome to know if I can target a specific profile).

TIA

**Comment by stephenlacy** [comment]
You should be able to pass the parameters directly to the full path of the executable file as the `app` option: https://github.com/stevelacy/gulp-open/blob/master/examples/gulpfile.js#L39

**Comment by colinrippeyfinarne** [comment]
> You should be able to pass the parameters directly to the full path of the executable file as the `app` option: https://github.com/stevelacy/gulp-open/blob/master/examples/gulpfile.js#L39

@stevelacy Thanks for the reply, for google chrome the full commandline for launching chrome using a specific profile looks like this:

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 15"

Is it possible to shoehorn in this?
