### ISSUE TITLE
open multiple urls in one window

### ISSUE THREAD

**Issue by soundyogi** [stevelacy/gulp-open#6]
i have a ticket system server and a dev server.

Is there anyway to open both urls in the same window?

thx in advance

**Comment by stevelacy** [comment]
Any updates?

**Comment by stephenstine** [comment]
Hi, I figured out a way to do this using ttab to open new terminal windows and child_process:

https://www.npmjs.com/package/ttab

`
var child_process = require('child_process');

gulp.task('openURL_01', function(){
  var options = {
    uri: 'http://localhost:8100/#',
    app: 'Google Chrome'
  };
  gulp.src('/')
  .pipe(open(options));
});

gulp.task('openURL_02', function(){
  var options = {
    uri: 'http://localhost:3000/',
    app: 'Google Chrome'
  };
  gulp.src('/')
  .pipe(open(options));
});

gulp.task('openMultipleTabs', ['openURL_01'], function(){

  child_process.exec('ttab sudo gulp openURL_02', function (err, stdout, stderr) {})

});
`

Now if you run the task openMultipleTabs, it will run the task openURL_01, opening Chrome and opening http://localhost:8100/# in Chrome first, then it will run openURL_02 after that, opening http://localhost:3000/ in another tab in the same Chrome window/instance
